# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# # # # Site settings # # # #
locale: "en"
lang:  "en-us"
title: "tati"
name:  "Tatiana Zihindula"
tagline: "Zzz"

baseurl: ''
url: ''

# # # # Build settings # # # #
encoding: "utf-8"

paginate: 5 # amount of posts to show
paginate_path: /page:num/
date_format:  "%b %-d, %Y" # http://shopify.github.io/liquid/filters/date/
    
# Exclude from processing.
# The following items will not be processed.
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CNAME
  - LICENSE
  - README
  - Gemfile
  - Gemfile.lock

include:
  - _pages
  - _data
